// Published dependency copy, independent of installation recipes and App metadata.
export const descriptions: Record<string, { en: string; zh: string; ja: string }> = {
  'apify-cli': { en: 'Develop, run and deploy Apify Actors from the command line.', zh: '在命令行开发、运行和部署 Apify Actor。', ja: 'コマンドラインで Apify Actor を開発・実行・デプロイします。' },
  bun: { en: 'Run JavaScript and TypeScript, install packages, bundle code and execute tests.', zh: '运行 JavaScript 和 TypeScript，安装依赖、打包代码和执行测试。', ja: 'JavaScript・TypeScript の実行、パッケージ管理、バンドル、テストに対応します。' },
  'document-node': { en: 'JavaScript libraries for creating Word, PowerPoint and PDF files and processing images.', zh: '用于生成 Word、PowerPoint、PDF 和处理图片的 JavaScript 库。', ja: 'Word・PowerPoint・PDF の生成と画像処理に使う JavaScript ライブラリです。' },
  'document-python': { en: 'Python libraries for reading, creating and converting documents, spreadsheets, PDFs and images.', zh: '用于读取、生成和转换文档、电子表格、PDF 及图片的 Python 库。', ja: '文書・スプレッドシート・PDF・画像の読み込み、生成、変換に使う Python ライブラリです。' },
  ffmpeg: { en: 'Convert, edit and inspect audio and video with FFmpeg and ffprobe.', zh: '使用 FFmpeg 和 ffprobe 转换、编辑和检查音视频。', ja: 'FFmpeg と ffprobe で音声・動画を変換、編集、解析します。' },
  git: { en: 'Track changes, manage branches and synchronize Git repositories.', zh: '跟踪代码变更、管理分支并同步 Git 仓库。', ja: '変更履歴の追跡、ブランチ管理、Git リポジトリの同期を行います。' },
  'github-cli': { en: 'Manage GitHub repositories, issues, pull requests and workflow runs with gh.', zh: '使用 gh 管理 GitHub 仓库、Issue、PR 和工作流运行。', ja: 'gh で GitHub リポジトリ、Issue、PR、ワークフロー実行を管理します。' },
  'gitlab-cli': { en: 'Manage GitLab projects, issues, merge requests and pipelines with glab.', zh: '使用 glab 管理 GitLab 项目、Issue、合并请求和流水线。', ja: 'glab で GitLab プロジェクト、Issue、マージリクエスト、パイプラインを管理します。' },
  go: { en: 'Build, test and format Go projects with go and gofmt.', zh: '使用 go 和 gofmt 编译、测试和格式化 Go 项目。', ja: 'go と gofmt で Go プロジェクトをビルド、テスト、整形します。' },
  libreoffice: { en: 'Convert Office documents and recalculate spreadsheet formulas with LibreOffice.', zh: '使用 LibreOffice 转换 Office 文档并重新计算电子表格公式。', ja: 'LibreOffice で Office 文書を変換し、スプレッドシートの数式を再計算します。' },
  micromamba: { en: 'Create isolated Conda environments and install native tools and libraries.', zh: '创建隔离的 Conda 环境，安装原生工具和库。', ja: '独立した Conda 環境を作成し、ネイティブツールとライブラリをインストールします。' },
  'native-build-tools': { en: 'Compile C and C++ code with compilers, Make, CMake and pkg-config.', zh: '提供 C/C++ 编译器、Make、CMake 和 pkg-config，用于原生代码构建。', ja: 'C/C++ コンパイラ、Make、CMake、pkg-config でネイティブコードをビルドします。' },
  pandoc: { en: 'Convert documents between Markdown, HTML, Word, LaTeX and other formats.', zh: '在 Markdown、HTML、Word、LaTeX 等文档格式之间转换。', ja: 'Markdown・HTML・Word・LaTeX などの文書形式を相互変換します。' },
  playwright: { en: 'Automate Chromium and run browser tests with Playwright and its CLI.', zh: '使用 Playwright 及其 CLI 自动操作 Chromium 并运行浏览器测试。', ja: 'Playwright と CLI で Chromium を自動操作し、ブラウザーテストを実行します。' },
  pnpm: { en: 'Install and manage JavaScript packages and monorepo workspaces with pnpm.', zh: '使用 pnpm 安装和管理 JavaScript 包及 monorepo 工作区。', ja: 'pnpm で JavaScript パッケージとモノレポのワークスペースを管理します。' },
  poppler: { en: 'Inspect PDFs, extract text and render pages as images with Poppler utilities.', zh: '使用 Poppler 工具检查 PDF、提取文本并将页面渲染为图片。', ja: 'Poppler ツールで PDF を解析し、テキスト抽出とページの画像化を行います。' },
  'postman-cli': { en: 'Run Postman API collections and tests from the command line.', zh: '在命令行运行 Postman API 集合和测试。', ja: 'コマンドラインで Postman の API コレクションとテストを実行します。' },
  'python-dev': { en: 'Lint and format Python code with Ruff and run tests with pytest.', zh: '使用 Ruff 检查和格式化 Python 代码，使用 pytest 运行测试。', ja: 'Ruff で Python コードを検査・整形し、pytest でテストを実行します。' },
  qpdf: { en: 'Check, repair, split, merge and transform PDF files with qpdf.', zh: '使用 qpdf 检查、修复、拆分、合并和转换 PDF 文件。', ja: 'qpdf で PDF ファイルの検査、修復、分割、結合、変換を行います。' },
  rust: { en: 'Build and test Rust projects with Cargo, format code and run Clippy checks.', zh: '使用 Cargo 构建和测试 Rust 项目，格式化代码并运行 Clippy 检查。', ja: 'Cargo で Rust プロジェクトをビルド・テストし、コード整形と Clippy の検査を行います。' },
  sentry: { en: 'Inspect Sentry errors and project data from the command line.', zh: '在命令行查看 Sentry 错误和项目数据。', ja: 'コマンドラインで Sentry のエラーとプロジェクトデータを確認します。' },
  'sentry-cli': { en: 'Manage Sentry releases and upload source maps and debug symbols.', zh: '管理 Sentry 发布版本，上传 source map 和调试符号。', ja: 'Sentry のリリースを管理し、ソースマップとデバッグシンボルをアップロードします。' },
  'shopify-cli': { en: 'Develop and deploy Shopify apps and themes from the command line.', zh: '在命令行开发和部署 Shopify 应用与主题。', ja: 'コマンドラインで Shopify アプリとテーマを開発・デプロイします。' },
  'stripe-cli': { en: 'Call Stripe APIs, forward webhooks and test payment integrations.', zh: '调用 Stripe API、转发 Webhook 并测试支付集成。', ja: 'Stripe API の呼び出し、Webhook の転送、決済連携のテストを行います。' },
  'supabase-cli': { en: 'Manage Supabase projects, database migrations and Edge Functions.', zh: '管理 Supabase 项目、数据库迁移和 Edge Functions。', ja: 'Supabase プロジェクト、データベース移行、Edge Functions を管理します。' },
  tesseract: { en: 'Extract text from images with the Tesseract OCR engine.', zh: '使用 Tesseract OCR 引擎从图片中识别和提取文本。', ja: 'Tesseract OCR エンジンで画像から文字を認識・抽出します。' },
  wrangler: { en: 'Develop and deploy Cloudflare Workers and manage their resources.', zh: '开发和部署 Cloudflare Workers，管理相关资源。', ja: 'Cloudflare Workers の開発・デプロイと関連リソースの管理を行います。' },
}
