# shellcheck shell=sh
# memoh-storage-layout: isolated
# Generated by scripts/dependencies/generate.ts; edit the source, then regenerate.
python3 - <<'MEMOH_RECIPE_PY'
import json
CONFIG = json.loads("{\"supported\":[\"linux/amd64\",\"linux/arm64\",\"darwin/arm64\"],\"backend\":\"github\",\"repo\":\"supabase/cli\",\"commands\":[\"supabase\"],\"assets\":{\"linux/amd64\":\"supabase_{version}_linux_amd64.tar.gz\",\"linux/arm64\":\"supabase_{version}_linux_arm64.tar.gz\",\"darwin/arm64\":\"supabase_{version}_darwin_arm64.tar.gz\"}}")
ACTION = "version"
"""Embedded in each generated recipe; no checkout or package-manager activation required."""
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.parse
import urllib.request
import uuid
import zipfile


def log(message):
    print(message, file=sys.stderr, flush=True)


def run(args, **kwargs):
    log(' '.join(map(str, args)))
    return subprocess.run(list(map(str, args)), check=True, **kwargs)


def capture(args, **kwargs):
    return run(args, stdout=subprocess.PIPE, text=True, **kwargs).stdout.strip()


def fetch(url):
    if not url.startswith('https://'):
        raise ValueError('Package metadata must use HTTPS')
    request = urllib.request.Request(url, headers={'User-Agent': 'Memoh-Supermarket', 'Accept': 'application/json'})
    with urllib.request.urlopen(request, timeout=90) as response:
        return response.read()


def remote_json(url):
    return json.loads(fetch(url))


def download(url, destination, digest=None):
    if not url.startswith('https://'):
        raise ValueError('Package downloads must use HTTPS')
    log('Downloading ' + url)
    request = urllib.request.Request(url, headers={'User-Agent': 'Memoh-Supermarket'})
    sha = hashlib.sha256()
    with urllib.request.urlopen(request, timeout=180) as response, destination.open('wb') as output:
        while chunk := response.read(1024 * 1024):
            output.write(chunk)
            sha.update(chunk)
    if digest and sha.hexdigest() != digest.removeprefix('sha256:'):
        destination.unlink()
        raise ValueError('SHA256 mismatch for ' + destination.name)


def unpack(archive, destination):
    destination.mkdir(parents=True, exist_ok=True)
    root = destination.resolve()
    def safe(name):
        if not (root / name).resolve().is_relative_to(root):
            raise ValueError('Archive path escapes installation: ' + name)
    if zipfile.is_zipfile(archive):
        with zipfile.ZipFile(archive) as source:
            for item in source.infolist():
                safe(item.filename)
                if (item.external_attr >> 16) & 0o170000 == 0o120000:
                    raise ValueError('Unexpected archive symlink')
            source.extractall(destination)
            for item in source.infolist():
                file = destination / item.filename
                if file.is_file():
                    file.chmod((item.external_attr >> 16 & 0o777) or 0o644)
    else:
        if not hasattr(tarfile, 'data_filter'):
            raise RuntimeError('Upgrade the Python dependency: archive extraction requires Python 3.12+ or its security backport')
        with tarfile.open(archive) as source:
            # data_filter also checks links, file types, and extraction order.
            source.extractall(destination, filter='data')


def wrapper(path, command, environment=None, prefix_args=(), restart_once=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ['#!/bin/sh', 'set -eu']
    for key, value in (environment or {}).items():
        lines.append('export ' + key + '=' + shlex.quote(str(value)))
    invocation = ' '.join(shlex.quote(str(x)) for x in [command, *prefix_args]) + ' "$@"'
    if restart_once:
        # LibreOffice EXITHELPER_NORMAL_RESTART (81): first-run profile setup.
        # Match its launcher without retrying crashes or looping indefinitely.
        lines += [invocation + ' && exit 0', 'status=$?', '[ "$status" -eq 81 ] || exit "$status"']
    lines.append('exec ' + invocation)
    path.write_text('\n'.join(lines) + '\n')
    path.chmod(0o755)


def release(config, version=None):
    repo = config['repo']
    endpoint = 'latest' if not version else 'tags/' + urllib.parse.quote(config.get('tag_prefix', 'v') + version, safe='')
    return remote_json(f'https://api.github.com/repos/{repo}/releases/{endpoint}')


def normalize_version(value):
    value = value.removeprefix('bun-v').removeprefix('v').removeprefix('go')
    if not re.fullmatch(r'[0-9][0-9A-Za-z.+_-]{0,99}', value):
        raise ValueError('Invalid release version')
    return value


def package_resolution(config, packages):
    if not isinstance(packages, dict) or set(packages) != set(config['packages']):
        raise ValueError('Saved package resolution does not match the approved package names')
    if any(not isinstance(value, str) or not value or any(char.isspace() for char in value) for value in packages.values()):
        raise ValueError('Saved package resolution contains an invalid package version')
    version = next(iter(packages.values())) if len(packages) == 1 else '0.0.0+' + hashlib.sha256(json.dumps(packages, sort_keys=True).encode()).hexdigest()[:16]
    return {'version': normalize_version(version), 'packages': packages}


def validate_saved_resolution(config, saved, expected):
    if not isinstance(saved, dict):
        raise ValueError('Saved package resolution is invalid')
    checked = package_resolution(config, saved.get('packages'))
    if checked['version'] != expected or saved.get('version') != expected:
        raise ValueError('Saved package resolution does not match the approved version')
    return checked


def resolve(config, requested, home, cache_home=None):
    backend = config['backend']
    requested = None if requested in ('', 'latest', 'stable', None) else normalize_version(requested)
    if backend == 'github':
        data = release(config, requested)
        return {'version': normalize_version(data['tag_name']), 'release': data}
    if backend in ('npm', 'python'):
        if requested and len(config['packages']) > 1:
            saved = home / 'resolutions' / (requested + '.json')
            if saved.is_file():
                return validate_saved_resolution(config, json.loads(saved.read_text()), requested)
        specs = {}
        for name in config['packages']:
            base_name = name.split('[')[0]
            if backend == 'npm':
                registry = os.environ.get('NPM_MIRROR', 'https://registry.npmjs.org').rstrip('/')
                tag = requested if requested and len(config['packages']) == 1 else 'latest'
                data = remote_json(registry + '/' + urllib.parse.quote(name, safe='@') + '/' + tag)
                specs[name] = data['version']
            else:
                suffix = f'/{requested}' if requested and len(config['packages']) == 1 else ''
                data = remote_json(f'https://pypi.org/pypi/{base_name}{suffix}/json')
                specs[name] = data['info']['version']
        resolution = package_resolution(config, specs)
        if requested and requested != resolution['version']:
            raise ValueError('The requested package resolution is unavailable')
        return resolution
    if backend == 'conda':
        version = requested or remote_json('https://api.anaconda.org/package/conda-forge/' + config['package'])['latest_version']
        return {'version': normalize_version(version)}
    if backend == 'go':
        data = remote_json('https://go.dev/dl/?mode=json' + ('&include=all' if requested else ''))
        item = next(row for row in data if row['stable'] and (not requested or row['version'] == 'go' + requested))
        return {'version': normalize_version(item['version']), 'files': item['files']}
    if backend == 'rust':
        channel = requested or 'stable'
        manifest = fetch(f'https://static.rust-lang.org/dist/channel-rust-{channel}.toml').decode()
        version = re.search(r'\[pkg\.rust\]\s+version = "([^ "\n]+)', manifest).group(1)
        return {'version': normalize_version(version)}
    if backend == 'gitlab':
        endpoint = requested and ('v' + requested) or 'permalink/latest'
        data = remote_json('https://gitlab.com/api/v4/projects/34675721/releases/' + endpoint)
        return {'version': normalize_version(data['tag_name']), 'release': data}
    if backend == 'postman':
        platform = config['platforms'][os.environ['MEMOH_DEP_OS'] + '/' + os.environ['MEMOH_DEP_ARCH']]
        request = urllib.request.Request('https://dl-cli.pstmn.io/download/latest/' + platform, method='HEAD')
        with urllib.request.urlopen(request, timeout=60) as response:
            filename = response.headers.get('Content-Disposition', '')
        version = requested or re.search(r'postman-cli-([0-9.]+)-', filename).group(1)
        return {'version': normalize_version(version), 'platform': platform}
    if backend == 'libreoffice':
        if os.environ['MEMOH_DEP_OS'] == 'linux':
            apt = apt_options(cache_home if cache_home is not None else home)
            run(['apt-get', *apt, 'update'], stdout=sys.stderr)
            version = capture(['apt-cache', *apt, 'policy', 'libreoffice-core'])
            version = re.search(r'Candidate:\s+(\S+)', version).group(1)
            if version == '(none)':
                raise ValueError('LibreOffice is unavailable from the configured Debian repositories')
            if requested:
                version = requested.replace('_', ':')
            return {'version': version.replace(':', '_'), 'debian_version': version}
        listing = fetch('https://download.documentfoundation.org/libreoffice/stable/').decode()
        versions = re.findall(r'href="(\d+\.\d+\.\d+(?:\.\d+)?)/"', listing)
        version = requested or max(versions, key=lambda v: tuple(map(int, v.split('.'))))
        return {'version': normalize_version(version)}
    raise ValueError('Unsupported installer: ' + backend)


def apt_options(home):
    cache = home / 'cache' / 'apt'
    for folder in ('lists/partial', 'archives/partial'):
        (cache / folder).mkdir(parents=True, exist_ok=True)
    status = cache / 'status'
    status.touch()
    # Empty status downloads the complete closure, including libraries that happen
    # to exist today. No package is installed into the host's root filesystem.
    return ['-o', 'Dir::State::status=' + str(status), '-o', 'Dir::State::lists=' + str(cache / 'lists'),
            '-o', 'Dir::Cache::archives=' + str(cache / 'archives'), '-o', 'Debug::NoLocking=1',
            '-o', 'APT::Sandbox::User=' + str(os.getuid())]


def relocate_libreoffice(root):
    # Debian's post-install scripts register these defaults with ucf. Recreate
    # only the private configuration, without running system post-install hooks.
    office = root / 'usr/lib/libreoffice'
    defaults = office / 'share/.registry'
    if defaults.is_dir():
        shutil.copytree(defaults, root / 'etc/libreoffice/registry', dirs_exist_ok=True)
    for link in root.rglob('*'):
        if link.is_symlink() and os.readlink(link).startswith('/'):
            destination = root / os.readlink(link).lstrip('/')
            link.unlink()
            link.symlink_to(os.path.relpath(destination, link.parent))
    for rc in (office / 'program').glob('*rc'):
        rc.write_text(rc.read_text().replace('file:///usr/', root.as_uri() + '/usr/')
                      .replace('file:///etc/', root.as_uri() + '/etc/'))


def install(config, resolution, target, home):
    backend = config['backend']
    version = resolution['version']
    commands = config['commands']
    platform = os.environ['MEMOH_DEP_OS'] + '/' + os.environ['MEMOH_DEP_ARCH']
    env = os.environ.copy()
    bin_dir = target / 'bin'
    bin_dir.mkdir()
    if backend == 'github':
        name = config['assets'][platform].format(version=version)
        asset = next(a for a in resolution['release']['assets'] if a['name'] == name)
        digest = asset.get('digest')
        if not digest or not digest.startswith('sha256:'):
            raise ValueError('Release does not publish an asset SHA256: ' + name)
        archive = target / name
        download(asset['browser_download_url'], archive, digest)
        if config.get('raw'):
            executable = target / 'payload' / commands[0]
            executable.parent.mkdir()
            archive.rename(executable)
            executable.chmod(0o755)
            wrapper(bin_dir / commands[0], executable)
        else:
            unpack(archive, target / 'payload')
            for command in commands:
                search = 'bun' if command == 'bunx' else command
                source = next(p for p in (target / 'payload').rglob(search) if p.is_file())
                source.chmod(0o755)
                wrapper(bin_dir / command, source, prefix_args=['x'] if command == 'bunx' else [])
            archive.unlink()
    elif backend == 'npm':
        prefix = target / 'npm'
        env.update(npm_config_cache=str(home / 'cache' / 'npm'), npm_config_update_notifier='false')
        specs = [f'{name}@{ver}' for name, ver in resolution['packages'].items()]
        run(['npm', 'install', '-g', '--prefix', prefix, '--include=optional', '--omit=dev', '--ignore-scripts',
             '--no-audit', '--no-fund', '--registry', env.get('NPM_MIRROR', 'https://registry.npmjs.org'), *specs], env=env, stdout=sys.stderr)
        exports = {'NODE_PATH': str(prefix / 'lib' / 'node_modules')}
        if config.get('playwright'):
            exports['PLAYWRIGHT_BROWSERS_PATH'] = str(target / 'browsers')
            exports['PLAYWRIGHT_SKIP_BROWSER_GC'] = '1'
            # The CLI defaults to system Chrome; this App installs Chromium.
            exports['PLAYWRIGHT_MCP_BROWSER'] = 'chromium'
            run([prefix / 'bin' / 'playwright', 'install', 'chromium'], env={**env, **exports}, stdout=sys.stderr)
        for command in commands:
            executable = shutil.which('node') if command == 'document-node' else prefix / 'bin' / command
            wrapper(bin_dir / command, executable, exports)
    elif backend == 'python':
        environment = target / 'venv'
        env['UV_CACHE_DIR'] = str(home / 'cache' / 'uv')
        # Own the interpreter as well as the venv: replacing the shared Python
        # dependency must not leave this bundle with a dangling interpreter.
        interpreter_dir = target / 'interpreter'
        run(['uv', 'python', 'install', '--no-bin', '--install-dir', interpreter_dir,
             '.'.join(map(str, sys.version_info[:3]))], env=env, stdout=sys.stderr)
        interpreter = next(interpreter_dir.glob('cpython-*/bin/python3'))
        run(['uv', 'venv', '--python', interpreter, environment], env=env, stdout=sys.stderr)
        run(['uv', 'pip', 'install', '--python', environment / 'bin' / 'python',
             *[f'{name}=={ver}' for name, ver in resolution['packages'].items()]], env=env, stdout=sys.stderr)
        for command in commands:
            executable = environment / 'bin' / ('python' if command == 'document-python' else command)
            wrapper(bin_dir / command, executable)
    elif backend == 'conda':
        prefix = target / 'environment'
        env['MAMBA_ROOT_PREFIX'] = str(home / 'cache' / 'mamba')
        specs = [config['package'] + '=' + version, *config.get('extra_packages', [])]
        run(['micromamba', '--no-rc', 'create', '--yes', '--prefix', prefix, '--override-channels',
             '--channel', 'conda-forge', '--strict-channel-priority', *specs], env=env, stdout=sys.stderr)
        for command in commands:
            executable = prefix / 'bin' / command
            if config.get('compiler') and command in ('cc', 'gcc', 'c++', 'g++'):
                executable = prefix / 'bin' / ('g++' if command in ('c++', 'g++') else 'gcc')
                if not executable.exists():
                    executable = prefix / 'bin' / ('clang++' if command in ('c++', 'g++') else 'clang')
            wrapper(bin_dir / command, executable)
    elif backend == 'go':
        item = next(f for f in resolution['files'] if f['os'] == os.environ['MEMOH_DEP_OS']
                    and f['arch'] == os.environ['MEMOH_DEP_ARCH'] and f['kind'] == 'archive')
        archive = target / item['filename']
        download('https://go.dev/dl/' + item['filename'], archive, item['sha256'])
        unpack(archive, target)
        archive.unlink()
        for command in commands:
            wrapper(bin_dir / command, target / 'go' / 'bin' / command, {'GOROOT': str(target / 'go')})
    elif backend == 'rust':
        triple = {'linux/amd64': 'x86_64-unknown-linux-gnu', 'linux/arm64': 'aarch64-unknown-linux-gnu',
                  'darwin/amd64': 'x86_64-apple-darwin', 'darwin/arm64': 'aarch64-apple-darwin'}[platform]
        url = 'https://static.rust-lang.org/rustup/dist/' + triple + '/rustup-init'
        checksum = fetch(url + '.sha256').decode().split()[0]
        init = target / 'rustup-init'
        download(url, init, checksum)
        init.chmod(0o755)
        exports = {'RUSTUP_HOME': str(target / 'rustup'), 'CARGO_HOME': str(target / 'cargo'), 'RUSTUP_INIT_SKIP_PATH_CHECK': 'yes'}
        run([init, '-y', '--no-modify-path', '--profile', 'minimal', '--default-toolchain', version,
             '--component', 'rustfmt', '--component', 'clippy'], env={**env, **exports}, stdout=sys.stderr)
        for command in commands:
            wrapper(bin_dir / command, target / 'cargo' / 'bin' / command, exports)
        init.unlink()
    elif backend == 'gitlab':
        arch = os.environ['MEMOH_DEP_ARCH']
        operating = os.environ['MEMOH_DEP_OS']
        name = f'glab_{version}_{operating}_{arch}.tar.gz'
        base = f'https://gitlab.com/gitlab-org/cli/-/releases/v{version}/downloads/'
        checksums = fetch(base + 'checksums.txt').decode()
        digest = next(line.split()[0] for line in checksums.splitlines() if line.split()[-1].lstrip('*') == name)
        archive = target / name
        download(base + name, archive, digest)
        unpack(archive, target / 'payload')
        wrapper(bin_dir / 'glab', next((target / 'payload').rglob('glab')))
        archive.unlink()
    elif backend == 'postman':
        archive = target / 'postman.tar.gz'
        # Postman distributes this archive directly over its official HTTPS host;
        # unlike GitHub releases, it does not publish a separate SHA256 manifest.
        download(f'https://dl-cli.pstmn.io/download/version/{version}/{resolution["platform"]}', archive)
        unpack(archive, target / 'payload')
        executable = next((target / 'payload').rglob('postman-cli'))
        executable.chmod(0o755)
        wrapper(bin_dir / 'postman', executable)
        archive.unlink()
    elif backend == 'libreoffice':
        if os.environ['MEMOH_DEP_OS'] == 'linux':
            archives = target / 'archives'
            (archives / 'partial').mkdir(parents=True)
            apt = [*apt_options(home), '-o', 'Dir::Cache::archives=' + str(archives)]
            run(['apt-get', *apt, '--yes', '--download-only', '--no-install-recommends', 'install',
                 *[name + '=' + resolution['debian_version'] for name in ['libreoffice-writer', 'libreoffice-calc', 'libreoffice-impress']]], stdout=sys.stderr)
            root = target / 'root'
            root.mkdir()
            for archive in sorted(archives.glob('*.deb')):
                run(['dpkg-deb', '--extract', archive, root], stdout=sys.stderr)
            shutil.rmtree(archives)
            relocate_libreoffice(root)
            triple = 'x86_64-linux-gnu' if os.environ['MEMOH_DEP_ARCH'] == 'amd64' else 'aarch64-linux-gnu'
            program = root / 'usr/lib/libreoffice/program'
            libraries = [program, root / 'usr/lib' / triple, root / 'lib' / triple, root / 'usr/lib']
            # Run against the extracted loader and matching libc, rather than
            # mixing a newer libc with the workspace image's dynamic loader.
            loader = next((root / 'lib' / triple).glob('ld-linux-*.so.*'), None)
            if loader is None:
                loader = next((root / 'usr/lib' / triple).glob('ld-linux-*.so.*'))
            for command in commands:
                wrapper(bin_dir / command, loader, {'SAL_USE_VCLPLUGIN': 'svp', 'URE_BOOTSTRAP': 'vnd.sun.star.pathname:' + str(program / 'fundamentalrc')},
                        ['--library-path', ':'.join(map(str, libraries)), program / 'soffice.bin'], restart_once=True)
        else:
            arch = 'aarch64' if os.environ['MEMOH_DEP_ARCH'] == 'arm64' else 'x86_64'
            name = f'LibreOffice_{version}_MacOS_{arch}.dmg'
            url = f'https://download.documentfoundation.org/libreoffice/stable/{version}/mac/{arch}/{name}'
            checksum = fetch(url + '.sha256').decode().split()[0]
            archive = target / name
            download(url, archive, checksum)
            mount = target / 'mount'
            mount.mkdir()
            run(['hdiutil', 'attach', '-nobrowse', '-readonly', '-mountpoint', mount, archive], stdout=sys.stderr)
            try:
                shutil.copytree(mount / 'LibreOffice.app', target / 'LibreOffice.app', symlinks=True)
            finally:
                run(['hdiutil', 'detach', mount], stdout=sys.stderr)
            archive.unlink()
            mount.rmdir()
            for command in commands:
                wrapper(bin_dir / command, target / 'LibreOffice.app/Contents/MacOS/soffice')
    else:
        raise ValueError('Unsupported backend')
    probe(config, target)


def probe(config, target):
    for command in config['commands']:
        args = config.get('probes', {}).get(command, ['--version'])
        run([target / 'bin' / command, *args], stdout=sys.stderr)
    if config.get('imports'):
        if config['backend'] == 'npm':
            run([target / 'bin' / config['commands'][0], '-e', ';'.join('require(' + json.dumps(name) + ')' for name in config['imports'])], stdout=sys.stderr)
        elif config['backend'] == 'python':
            run([target / 'venv' / 'bin' / 'python', '-c', ';'.join('import ' + name for name in config['imports'])], stdout=sys.stderr)


def newer(latest, installed):
    if not installed:
        return True
    if '+' in latest or '+' in installed:
        return latest != installed
    return tuple(map(int, re.findall(r'\d+', latest))) > tuple(map(int, re.findall(r'\d+', installed)))


def main(config, action):
    home = Path(os.environ['MEMOH_DEP_HOME'])
    if not home.is_absolute() or home.resolve() == Path('/') or home.is_symlink():
        raise ValueError('Unsafe dependency home')
    platform = os.environ['MEMOH_DEP_OS'] + '/' + os.environ['MEMOH_DEP_ARCH']
    if platform not in config['supported'] or (platform.startswith('linux/') and os.environ.get('MEMOH_DEP_LIBC', 'glibc') != 'glibc'):
        raise ValueError('Unsupported platform: ' + platform)
    result_path = Path(os.environ['MEMOH_DEP_RESULT'])
    if action == 'version':
        target = Path(os.environ['MEMOH_DEP_CANDIDATE']).parent.parent.resolve()
        probe(config, target)
        resolution = json.loads((target / 'resolution.json').read_text())
        if config.get('backend') in ('npm', 'python'):
            resolution = validate_saved_resolution(config, resolution, resolution['version'])
        result_path.write_text(json.dumps({'version': resolution['version']}))
        return
    store = Path(os.environ.get('MEMOH_DEP_STORE') or home)
    if not store.is_absolute() or store.resolve() == Path('/') or store.is_symlink():
        raise ValueError('Unsafe dependency store')
    isolated = bool(os.environ.get('MEMOH_DEP_INSTALL_DIR'))
    if action == 'remove':
        if not isolated and home.exists():
            shutil.rmtree(home)
        result_path.write_text('{}')
        return
    resolution = resolve(config, '' if action == 'check_update' else os.environ.get('MEMOH_DEP_VERSION', ''), home, store)
    version = resolution['version']
    history = home / 'resolutions'
    history.mkdir(parents=True, exist_ok=True)
    (history / (version + '.json')).write_text(json.dumps(resolution))
    if action == 'check_update':
        installed = os.environ.get('MEMOH_DEP_CURRENT_VERSION', '')
        result_path.write_text(json.dumps({'installed': installed, 'latest': version, 'update_available': newer(version, installed)}))
        return
    versions = home / 'versions'
    if not isolated:
        versions.mkdir(parents=True, exist_ok=True)
    # Install in its permanent location: venv/Conda/rustup embed absolute paths.
    # Only current changes. Failed installs cannot touch any previous version.
    target = Path(os.environ['MEMOH_DEP_INSTALL_DIR']) if isolated else versions / (version + '-' + uuid.uuid4().hex[:12])
    if isolated and (target.parent != store / 'installs' or target.is_symlink()):
        raise ValueError('Unsafe installation directory')
    target.parent.mkdir(parents=True, exist_ok=True)
    target.mkdir()
    activated = False
    try:
        install(config, resolution, target, store)
        (target / 'resolution.json').write_text(json.dumps(resolution))
        result = {'version': version, 'entrypoints': {cmd: str(home / 'current/bin' / cmd) for cmd in config['commands']}}
        # A result-write failure must occur before publication.
        result_path.write_text(json.dumps(result))
        if isolated:
            # Absolute paths embedded by venv/Conda require the permanent unique
            # directory. The Server alone publishes current after verification.
            operation = Path(os.environ['MEMOH_DEP_OPERATION_DIR'])
            (operation / 'candidate').write_text(str(target))
            activated = True
            return
        temporary = home / ('current-' + uuid.uuid4().hex)
        try:
            temporary.symlink_to(target)
            os.replace(temporary, home / 'current')
            activated = True
        finally:
            temporary.unlink(missing_ok=True)
    finally:
        if not activated:
            shutil.rmtree(target)


if __name__ == '__main__':
    main(CONFIG, ACTION)

MEMOH_RECIPE_PY
